login_secret_key: "+jRCqBlpa4Mqo558EVWfioZAIfiFEHgQvN6BxD7qBgQ="
admin_team_id: 4b45bb80-9a8b-47ca-ad0d-a995b1ffe6d6
redis:
  host: localhost
  port: 6379
  password: abcd
postgres:
  host: localhost
  port: 5432
  user: abcd
  password: abcd
  database: abcd
in_cluster: false
redis_resync_interval: 60
dev: false
url: "https://instancer.example.com"
challenge_host: instancer.example.com
rctf_mode: true
rctf_url: "https://rctf.example.com"
session_length: 86400
recaptcha_site_key: "recaptchasitekeyobtainedfromgoogle"
recaptcha_secret: "recaptchasecretobtainedfromgoogle"
