version: "3.9"
services:
  web:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./k3s.yaml:/app/.kube/config:ro
      - ./config.yml:/app/config.yml:ro
    environment:
      - KUBECONFIG=/app/.kube/config
    depends_on:
      - redis-service
      - db
  # worker:
  #   build: .
  #   volumes:
  #     - ./k3s.yaml:/app/.kube/config:ro
  #     - ./config.yml:/app/config.yml:ro
  #   environment:
  #     - KUBECONFIG=/app/.kube/config
  #   command: ["python", "worker.py"]
  redis-service:
    image: "redis:alpine"
  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=Q7FHcs0R2TQYqFyP92OD
      - POSTGRES_USER=instancer
      - POSTGRES_DB=instancer
    volumes:
      - ./fixture.sql:/docker-entrypoint-initdb.d/fixture.sql:ro
      - instancerdb:/var/lib/postgresql/data
volumes:
  instancerdb:
