version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./k3s.yaml:/app/.kube/config:ro
    environment:
      - KUBECONFIG=/app/.kube/config
  redis-service:
    image: "redis:alpine"
