services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: queue
      POSTGRES_PASSWORD: BnA6tObcPm44I7RMb1Xqajs5UYl5LWsMMC4BYpHwoPp6jc7Tk4
  queue:
    build: queue/
    restart: always
    ports:
      - "3001:3001"
    environment:
      startTime: 1674372589
      POSTGRES_USER: queue
      POSTGRES_PASSWORD: BnA6tObcPm44I7RMb1Xqajs5UYl5LWsMMC4BYpHwoPp6jc7Tk4
      FLAG_SERVER_URL: http://localhost:3000
      PORT: 3001
      ADMIN_SECRET: "0wN7Q3JQC9Ae4Q9M1kXaserN5byNmvMjHDSsvmjvvh2gYUeBfZnTUNlo"
    depends_on:
      - "db"
  flagserver:
    build: flagserver/
    restart: always
    ports:
      - "3000:3000"
    environment:
      QUEUE_SERVER_URL: http://localhost:3001
      QUEUE_SERVER_PORT: 3001
      FLAG: lactf{test}
      PORT: 3000
      ADMIN_SECRET: "0wN7Q3JQC9Ae4Q9M1kXaserN5byNmvMjHDSsvmjvvh2gYUeBfZnTUNlo"
    depends_on:
      - "queue"
